services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 80:80

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: TestUser
      MYSQL_PASSWORD: TestUserForLocalhost
      MYSQL_DATABASE: kennethclemmensen_test_db
    build:
      dockerfile_inline: |
        FROM mysql:8.0.33
        ADD https://raw.githubusercontent.com/kennethclemmensen/kennethclemmensen.dk/master/tests/_data/dump.sql /docker-entrypoint-initdb.d
        RUN chmod -R 777 /docker-entrypoint-initdb.d