services:
  app:
    build: ./app
    depends_on:
      - db
    ports:
      - 80:80

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: TestUser
      MYSQL_PASSWORD: TestUserForLocalhost
      MYSQL_DATABASE: kennethclemmensen_test_db
    build: ./db