<?php
$path = __DIR__.'/includes';
require_once "$path/Action.php";
require_once "$path/Filter.php";
require_once "$path/Pagination.php";
require_once "$path/ThemeActivator.php";
require_once "$path/ThemeService.php";
require_once "$path/api/ApiClient.php";
require_once "$path/mobile-menu/MobileMenuAnimation.php";
require_once "$path/mobile-menu/MobileMenuWalker.php";
require_once "$path/settings/BaseSettings.php";
require_once "$path/settings/ContactSettings.php";
require_once "$path/settings/GallerySettings.php";
require_once "$path/settings/MobileMenuSettings.php";
require_once "$path/settings/ScriptSettings.php";
require_once "$path/settings/SliderSettings.php";
require_once "$path/settings/ThemeSettings.php";
require_once "$path/slider/SliderAnimation.php";
require_once "$path/translations/TranslationStrings.php";
require_once "$path/widgets/IconWidget.php";
$themeActivator = new ThemeActivator();
$themeActivator->activate();
$themeActivator->run();