name: deploy-plugin

on:
  # Triggers the workflow on the push event but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'public/wp-content/plugins/kc/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3.1.0

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        protocol: ftps
        port: 21
        local-dir: public/wp-content/plugins/kc/
        server-dir: public_html/wp-content/plugins/kc/