# This is a basic workflow to help you get started with Actions

name: deploy-kc-plugin-action

# Controls when the action will run. 
on:
  # Triggers the workflow on the push event but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'public/wp-content/plugins/kc/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: linux75.unoeuro.com
        username: kennethclemmense.dk
        password: ${{ secrets.password }}
        protocol: ftps
        port: 21