name: deploy-theme

on:
  # Triggers the workflow on the push event but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'public/wp-content/themes/kennethclemmensen/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4.1.1

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        protocol: ftps
        port: 21
        local-dir: public/wp-content/themes/kennethclemmensen/
        server-dir: public_html/wp-content/themes/kennethclemmensen/
        exclude: |
          public/wp-content/themes/kennethclemmensen/css/compiled
          public/wp-content/themes/kennethclemmensen/js/compiled
          public/wp-content/themes/kennethclemmensen/less
          public/wp-content/themes/kennethclemmensen/sass
          public/wp-content/themes/kennethclemmensen/ts